AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AwsIotButtonDsn:
    Type: String
    Default: XXXXXXXXXXXXXXXX
    Description: Enter the DSN of your IoT button

Resources:

  DashboardApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "lambda_function.lambda_handler"
      Runtime: "python2.7"
      Role: !GetAtt ButtonLambdaRole.Arn
      CodeUri: s3://alex-mattson-demo-code/dashboard_lambda_function.zip
      Environment:
        Variables:
          lap_count_table: !Ref LapTable
          button_dsn: !Ref AwsIotButtonDsn
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get

  ButtonPressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "lambda_function.lambda_handler"
      Runtime: "python2.7"
      Role: !GetAtt ButtonLambdaRole.Arn
      CodeUri: s3://alex-mattson-demo-code/button_lambda_function.zip
      Environment:
        Variables:
          lap_count_table: !Ref LapTable
          button_dsn: !Ref AwsIotButtonDsn

  LapTable:
     Type: AWS::DynamoDB::Table
     Properties:
       AttributeDefinitions:
         - AttributeName: deviceId
           AttributeType: S
       KeySchema:
         - AttributeName: deviceId
           KeyType: HASH
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1

  DashboardBucket:
    Type: AWS::S3::Bucket

  ButtonLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "lambdaResourceAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "dynamodb:*"
                Resource:
                  - !Join ["", ["arn:aws:dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref LapTable]]
              -
                Effect: "Allow"
                Action: "logs:CreateLogGroup"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
